begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select plan(17);
insert into auth.users(id,email) values('f3111111-1111-4111-8111-111111111111','break-student@example.com'),('f3222222-2222-4222-8222-222222222222','break-other@example.com');
update public.profiles set role='student' where id in ('f3111111-1111-4111-8111-111111111111','f3222222-2222-4222-8222-222222222222');
set local request.jwt.claim.sub='f3111111-1111-4111-8111-111111111111';
set local role authenticated;
select public.upsert_focus_plan('break-plan','{"title": "차단 집중", "description": "", "dateKey": "2026-10-02", "plannedStartAt": null, "targetFocusMinutes": 5, "activityMode": "interactive", "blockingMode": "off", "allowedDomains": [], "blockedDomains": [], "breakMinutes": 1, "priority": "medium", "selfDepositPoints": 0, "guardianRewardRequestPoints": 0, "goals": [{"id": "g1", "name": "목표", "detail": "", "minutes": 5, "priority": "medium"}], "status": "ready", "createdAt": "2026-10-02T00:00:00Z", "updatedAt": "2026-10-02T00:00:00Z"}','device');
create temporary table break_session as select public.start_focus_session('break-plan','device') payload;
create temporary table first_break as select public.start_focus_break((select payload->>'id' from break_session),'device','a1111111-1111-4111-8111-111111111111') payload;
select is((select payload->>'pauseKind' from first_break),'break','timed break is distinct from manual pause');
select is((select (payload->>'breakEndsAt')::timestamptz-(payload->>'breakStartedAt')::timestamptz from first_break),interval '60 seconds','server sets configured break deadline');
select is(public.start_focus_break((select payload->>'id' from break_session),'device','a1111111-1111-4111-8111-111111111111')->>'breakEndsAt',(select payload->>'breakEndsAt' from first_break),'duplicate request does not extend break');
set local request.jwt.claim.sub='f3222222-2222-4222-8222-222222222222';
select throws_ok($$select public.start_focus_break((select payload->>'id' from break_session),'device','a2222222-2222-4222-8222-222222222222')$$,'P0001','focus session not found','other user cannot start break');
set local request.jwt.claim.sub='f3111111-1111-4111-8111-111111111111';
reset role;
update public.cloud_focus_sessions set payload=payload||jsonb_build_object('breakStartedAt',now()-interval '20 seconds') where entity_id=(select payload->>'id' from break_session);
set local role authenticated;
create temporary table early_resume as select public.resume_focus_session((select payload->>'id' from break_session),'device') payload;
select is((select payload->>'status' from early_resume),'active','manual early return resumes focus');
select is((select (payload->>'accumulatedBreakSeconds')::integer from early_resume),20,'only elapsed break consumes budget');
select is((select payload->>'breakEndsAt' from early_resume),null::text,'early return clears deadline');
select is(public.start_focus_break((select payload->>'id' from break_session),'device','a1111111-1111-4111-8111-111111111111')->>'status','active','late duplicate cannot create another break');
create temporary table second_break as select public.start_focus_break((select payload->>'id' from break_session),'device','a2222222-2222-4222-8222-222222222222') payload;
select is((select (payload->>'breakEndsAt')::timestamptz-(payload->>'breakStartedAt')::timestamptz from second_break),interval '40 seconds','next break uses remaining total budget');
reset role;
update public.cloud_focus_sessions set payload=payload||jsonb_build_object('breakStartedAt',now()-interval '50 seconds','breakEndsAt',now()-interval '10 seconds') where entity_id=(select payload->>'id' from break_session);
set local role authenticated;
create temporary table automatic_resume as select public.get_focus_session((select payload->>'id' from break_session)) payload;
select is((select payload->>'status' from automatic_resume),'active','expired break resumes on canonical read');
select is((select (payload->>'activeSegmentStartedAt')::timestamptz from automatic_resume),now()-interval '10 seconds','automatic return uses absolute deadline');
select is((select (payload->>'accumulatedBreakSeconds')::integer from automatic_resume),60,'automatic return consumes remaining break budget once');
select throws_ok($$select public.start_focus_break((select payload->>'id' from break_session),'device','a3333333-3333-4333-8333-333333333333')$$,'P0001','break budget exhausted','breaks cannot exceed configured total');
select ok(not has_function_privilege('anon','public.start_focus_break(text,text,uuid)','EXECUTE'),'anonymous break request rejected');
create temporary table manual_pause as select public.pause_focus_session((select payload->>'id' from break_session),'device') payload;
select is((select payload->>'pauseKind' from manual_pause),'manual','manual pause remains separate after break budget is exhausted');
select is((select payload->>'breakEndsAt' from manual_pause),null::text,'manual pause has no automatic deadline');
reset role;
update public.cloud_focus_sessions set payload=jsonb_set(payload,'{endsAt}',to_jsonb(now()-interval '1 hour')) where entity_id=(select payload->>'id' from break_session);
set local role authenticated;
select is(public.get_focus_session((select payload->>'id' from break_session))->>'status','paused','manual pause does not expire with old focus deadline');
select * from finish();
rollback;
