begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select plan(15);
insert into auth.users(id,email) values('f3111111-1111-4111-8111-111111111111','plan-student@example.com'),('f3222222-2222-4222-8222-222222222222','plan-other@example.com');
update public.profiles set role='student',onboarding_completed=true where id in ('f3111111-1111-4111-8111-111111111111','f3222222-2222-4222-8222-222222222222');
set local request.jwt.claim.sub='f3111111-1111-4111-8111-111111111111';
set local role authenticated;
create temporary table saved_plan as select public.upsert_focus_plan('editable-plan','{"title":"차단 집중","description":"","dateKey":"2026-10-02","plannedStartAt":null,"targetFocusMinutes":5,"activityMode":"interactive","blockingMode":"blocklist","allowedDomains":[],"blockedDomains":[{"hostname":"youtube.com","includeSubdomains":true}],"breakMinutes":5,"priority":"medium","selfDepositPoints":1000,"guardianRewardRequestPoints":0,"goals":[{"id":"g1","name":"목표","detail":"","minutes":5,"priority":"medium"}],"status":"planned","createdAt":"2026-10-02T00:00:00Z","updatedAt":"2026-10-02T00:00:00Z"}','device') payload;
select is((select payload->>'dateKey' from saved_plan),'2026-10-02','selected date is preserved');
create temporary table edited_plan as select public.upsert_focus_plan('editable-plan',(select payload||'{"title":"수정한 계획","dateKey":"2026-10-05","createdAt":"2030-01-01T00:00:00Z"}' from saved_plan),'device') payload;
select is((select payload->>'dateKey' from edited_plan),'2026-10-05','edit persists selected new date');
select is((select payload->>'id' from edited_plan),'editable-plan','edit preserves identity');
select is((select payload->>'createdAt' from edited_plan),(select payload->>'createdAt' from saved_plan),'edit preserves original creation time');
select throws_ok($$select public.upsert_focus_plan('editable-plan',(select payload from saved_plan),'device')$$,'P0001','focus plan changed; reload required','stale edit cannot overwrite newer plan');
reset role;
insert into public.wallet_transactions(kind,status,from_user_id,to_user_id,points,schedule_id,idempotency_key)
values('guardian_reward_requested','pending','f3111111-1111-4111-8111-111111111111','f3222222-2222-4222-8222-222222222222',100,'editable-plan','plan-pending-reward');
set local role authenticated;
select throws_ok($$select public.upsert_focus_plan('editable-plan',(select payload from edited_plan),'device')$$,'P0001','focus plan has a pending guardian request','pending reward protects settings');
select throws_ok($$select public.cancel_focus_plan('editable-plan',(select (payload->>'updatedAt')::timestamptz from edited_plan))$$,'P0001','focus plan has a pending guardian request','pending reward prevents cancellation');
select throws_ok($$select public.cancel_focus_plan('editable-plan',(select (payload->>'updatedAt')::timestamptz from saved_plan))$$,'P0001','focus plan changed; reload required','stale cancellation cannot cancel revised plan');
reset role;
delete from public.wallet_transactions where idempotency_key='plan-pending-reward';
insert into public.cloud_focus_sessions(user_id,entity_id,payload,version,device_id) values('f3111111-1111-4111-8111-111111111111','unfinished-plan-session','{"scheduleId":"editable-plan","status":"starting"}',1,'device');
set local role authenticated;
select throws_ok($$select public.upsert_focus_plan('editable-plan',(select payload from edited_plan),'device')$$,'P0001','focus plan has an unfinished session','pending enforcement locks plan');
select throws_ok($$select public.cancel_focus_plan('editable-plan',(select (payload->>'updatedAt')::timestamptz from edited_plan))$$,'P0001','focus plan has an unfinished session','pending enforcement prevents cancellation');
reset role;
delete from public.cloud_focus_sessions where entity_id='unfinished-plan-session';
set local role authenticated;
set local request.jwt.claim.sub='f3222222-2222-4222-8222-222222222222';
select throws_ok($$select public.cancel_focus_plan('editable-plan',(select (payload->>'updatedAt')::timestamptz from edited_plan))$$,'P0001','focus plan not found','another student cannot cancel plan');
set local request.jwt.claim.sub='f3111111-1111-4111-8111-111111111111';
select is(public.cancel_focus_plan('editable-plan',(select (payload->>'updatedAt')::timestamptz from edited_plan))->>'status','cancelled','unused plan is cancelled');
select is(public.cancel_focus_plan('editable-plan',(select (payload->>'updatedAt')::timestamptz from edited_plan))->>'status','cancelled','repeat cancellation is idempotent');
select throws_ok($$select public.upsert_focus_plan('editable-plan',(select payload from edited_plan),'device')$$,'P0001','focus plan cannot be edited','cancelled plans cannot be resurrected');
select ok(not has_function_privilege('anon','public.cancel_focus_plan(text,timestamptz)','EXECUTE'),'anonymous cancellation is denied');
select * from finish();
rollback;
