begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select plan(11);
insert into auth.users(id,email) values('f3111111-1111-4111-8111-111111111111','policy-student@example.com');
update public.profiles set role='student' where id='f3111111-1111-4111-8111-111111111111';
insert into public.wallet_transactions(kind,status,to_user_id,from_bucket,to_bucket,points,idempotency_key) values('topup_confirmed','posted','f3111111-1111-4111-8111-111111111111','external','topup',5000,'policy-topup');
set local request.jwt.claim.sub='f3111111-1111-4111-8111-111111111111';
set local role authenticated;
select public.upsert_focus_plan('policy-partial','{"title": "차단 집중", "description": "", "dateKey": "2026-10-02", "plannedStartAt": null, "targetFocusMinutes": 1, "activityMode": "interactive", "blockingMode": "off", "allowedDomains": [], "blockedDomains": [], "breakMinutes": 5, "priority": "medium", "selfDepositPoints": 1000, "guardianRewardRequestPoints": 0, "goals": [{"id": "g1", "name": "첫 목표", "detail": "", "minutes": 1, "priority": "medium"}, {"id": "g2", "name": "둘째 목표", "detail": "", "minutes": 1, "priority": "medium"}], "status": "ready", "createdAt": "2026-10-02T00:00:00Z", "updatedAt": "2026-10-02T00:00:00Z", "depositPolicy": {"version": 1, "mode": "tiered"}}','device');
create temporary table policy_partial as select public.start_focus_session('policy-partial','device') payload;
select is((select payload->'depositPolicy' from policy_partial),'{"version":2,"mode":"all-or-none"}'::jsonb,'server sets new policy regardless of client plan field');
select throws_ok($$select public.finish_focus_session((select payload->>'id' from policy_partial),array['g1','g2'],'device')$$,'P0001','focus session has not reached target time','full goal selection cannot bypass target time');
reset role;
update public.cloud_focus_sessions set payload=jsonb_set(payload,'{endsAt}',to_jsonb(now()-interval '1 second')) where entity_id=(select payload->>'id' from policy_partial);
set local role authenticated;
create temporary table policy_partial_result as select public.finish_focus_session((select payload->>'id' from policy_partial),array['g1'],'device') payload;
select is((select payload->>'status' from policy_partial_result),'failed','partial completion cannot become a successful v3 session');
select is((select payload->>'status' from public.cloud_schedules where entity_id='policy-partial'),'failed','plan completion agrees with the v3 session result');
select is((select (payload->'result'->>'earnedPoints')::integer from policy_partial_result),0,'partial v3 completion earns no deposit');
select is((select (payload->'result'->>'returnedPoints')::integer from policy_partial_result),1000,'partial v3 completion returns full deposit');
select is(public.finish_focus_session((select payload->>'id' from policy_partial),array['g1'],'device')->'result',(select payload->'result' from policy_partial_result),'repeat finish preserves settlement');
select public.upsert_focus_plan('policy-full','{"title": "차단 집중", "description": "", "dateKey": "2026-10-02", "plannedStartAt": null, "targetFocusMinutes": 1, "activityMode": "interactive", "blockingMode": "off", "allowedDomains": [], "blockedDomains": [], "breakMinutes": 5, "priority": "medium", "selfDepositPoints": 1000, "guardianRewardRequestPoints": 0, "goals": [{"id": "g1", "name": "첫 목표", "detail": "", "minutes": 1, "priority": "medium"}, {"id": "g2", "name": "둘째 목표", "detail": "", "minutes": 1, "priority": "medium"}], "status": "ready", "createdAt": "2026-10-02T00:00:00Z", "updatedAt": "2026-10-02T00:00:00Z", "depositPolicy": {"version": 1, "mode": "tiered"}}','device');
create temporary table policy_full as select public.start_focus_session('policy-full','device') payload;
reset role;
update public.cloud_focus_sessions set payload=jsonb_set(payload,'{endsAt}',to_jsonb(now()-interval '1 second')) where entity_id=(select payload->>'id' from policy_full);
set local role authenticated;
create temporary table policy_full_result as select public.finish_focus_session((select payload->>'id' from policy_full),array['g1','g2'],'device') payload;
select is((select payload->>'status' from policy_full_result),'success','full v3 completion succeeds');
select is((select (payload->'result'->>'earnedPoints')::integer from policy_full_result),1000,'full v3 completion earns entire deposit');
select is((select (payload->'walletBalances'->>'reservedAvailable')::integer from policy_full_result),0,'settled sessions leave no reserved balance');
select is((select count(*) from public.wallet_transactions where kind='self_deposit_earned'),1::bigint,'only fully successful v3 session posts earned transaction');
select * from finish();
rollback;
