begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select plan(16);
insert into auth.users(id,email) values('f3111111-1111-4111-8111-111111111111','enforcement-student@example.com'),('f3222222-2222-4222-8222-222222222222','enforcement-other@example.com');
update public.profiles set role='student',onboarding_completed=true where id in ('f3111111-1111-4111-8111-111111111111','f3222222-2222-4222-8222-222222222222');
insert into public.wallet_transactions(kind,status,to_user_id,from_bucket,to_bucket,points,idempotency_key) values('topup_confirmed','posted','f3111111-1111-4111-8111-111111111111','external','topup',5000,'enforcement-topup');
set local request.jwt.claim.sub='f3111111-1111-4111-8111-111111111111';
set local role authenticated;
select public.upsert_focus_plan('enforcement-plan','{"title":"차단 집중","description":"","dateKey":"2026-10-02","plannedStartAt":null,"targetFocusMinutes":5,"activityMode":"interactive","blockingMode":"blocklist","allowedDomains":[],"blockedDomains":[{"hostname":"youtube.com","includeSubdomains":true}],"breakMinutes":5,"priority":"medium","selfDepositPoints":1000,"guardianRewardRequestPoints":0,"goals":[{"id":"g1","name":"목표","detail":"","minutes":5,"priority":"medium"}],"status":"ready","createdAt":"2026-10-02T00:00:00Z","updatedAt":"2026-10-02T00:00:00Z"}','device');
create temporary table enforcement_started as select public.start_focus_session('enforcement-plan','device') payload;
select is((select payload->>'status' from enforcement_started),'starting','enforced focus waits for extension application');
select is((select count(*) from public.notifications where kind='focus_started'),0::bigint,'pending application does not announce focus started');
select is(public.start_focus_session('enforcement-plan','device')->>'id',(select payload->>'id' from enforcement_started),'repeated start reuses same pending session');
select is((select count(*) from public.wallet_transactions where kind='self_deposit_reserved'),1::bigint,'repeated start reserves once');
set local request.jwt.claim.sub='f3222222-2222-4222-8222-222222222222';
select throws_ok($$select public.confirm_focus_enforcement((select payload->>'id' from enforcement_started),'device')$$,'P0001','focus session not found','another user cannot acknowledge enforcement');
set local request.jwt.claim.sub='f3111111-1111-4111-8111-111111111111';
select is(public.confirm_focus_enforcement((select payload->>'id' from enforcement_started),'extension-device')->>'status','active','application acknowledgement activates focus');
select is(public.confirm_focus_enforcement((select payload->>'id' from enforcement_started),'extension-device')->>'endsAt',(select payload->>'endsAt' from public.cloud_focus_sessions where entity_id=(select payload->>'id' from enforcement_started)),'acknowledgement does not extend twice');
select is((select count(*) from public.notifications where kind='focus_started'),1::bigint,'activation announces once');
select is(public.cancel_focus_start((select payload->>'id' from enforcement_started),'device')->>'status','active','late timeout cannot cancel a committed activation');
reset role;
update public.cloud_focus_sessions set payload=jsonb_set(payload,'{endsAt}',to_jsonb(now()-interval '1 second')) where entity_id=(select payload->>'id' from enforcement_started);
set local role authenticated;
select public.finish_focus_session((select payload->>'id' from enforcement_started),array['g1']::text[],'device');
reset role;
update public.cloud_schedules set payload=payload||'{"status":"ready"}' where entity_id='enforcement-plan';
set local role authenticated;
create temporary table enforcement_cancel as select public.start_focus_session('enforcement-plan','device') payload;
select is(public.cancel_focus_start((select payload->>'id' from enforcement_cancel),'device')->>'status','cancelled','failed application can cancel pending start');
select is(public.cancel_focus_start((select payload->>'id' from enforcement_cancel),'device')->>'status','cancelled','pending cancellation is idempotent');
reset role;
select is((select count(*) from public.wallet_transactions where kind='self_deposit_returned'),1::bigint,'cancellation returns reserved self deposit once');
set local role authenticated;
create temporary table enforcement_expired as select public.start_focus_session('enforcement-plan','device') payload;
reset role;
update public.cloud_focus_sessions set payload=jsonb_set(payload,'{enforcementDeadlineAt}',to_jsonb(now()-interval '1 second')) where entity_id=(select payload->>'id' from enforcement_expired);
set local role authenticated;
select is(public.get_focus_session((select payload->>'id' from enforcement_expired))->>'status','cancelled','expired application is cancelled during recovery');
reset role;
select is((select count(*) from public.wallet_transactions where kind='self_deposit_returned'),2::bigint,'deadline recovery returns reserved deposit');
select is((public.get_wallet_balances('f3111111-1111-4111-8111-111111111111')->>'reservedAvailable')::bigint,0::bigint,'cancelled starts leave no reserved self points');
select ok(not has_function_privilege('anon','public.confirm_focus_enforcement(text,text)','EXECUTE'),'anonymous cannot confirm application');
select * from finish();
rollback;
