begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select plan(41);
insert into auth.users(id,email) values
 ('b1111111-1111-4111-8111-111111111111','reward-student@example.com'),
 ('b2222222-2222-4222-8222-222222222222','reward-guardian@example.com');
update public.profiles set role='student',display_name='보상 학생' where id='b1111111-1111-4111-8111-111111111111';
update public.profiles set role='guardian',display_name='보상 보호자' where id='b2222222-2222-4222-8222-222222222222';
insert into public.family_links(student_user_id,guardian_user_id,issuer_user_id,issuer_role,status,linked_at)
values('b1111111-1111-4111-8111-111111111111','b2222222-2222-4222-8222-222222222222','b2222222-2222-4222-8222-222222222222','guardian','active',now());
insert into public.wallet_transactions(kind,status,from_user_id,to_user_id,from_bucket,to_bucket,points,krw_amount,provider,provider_order_id,provider_payment_key,idempotency_key,metadata)
values('topup_confirmed','posted',null,'b2222222-2222-4222-8222-222222222222','external','topup',10000,10000,'toss','reward-topup-order','test-payment','reward-topup-confirmed','{}');

insert into public.wallet_transactions(kind,status,to_user_id,from_bucket,to_bucket,points,idempotency_key) values('topup_confirmed','posted','b1111111-1111-4111-8111-111111111111','external','topup',5000,'student-approval-test-topup');
set local request.jwt.claim.sub='b1111111-1111-4111-8111-111111111111';
set local role authenticated;
select public.upsert_focus_plan('reward-plan-1','{"title":"보상 집중","description":"","dateKey":"2026-08-24","plannedStartAt":null,"targetFocusMinutes":5,"activityMode":"interactive","blockingMode":"off","allowedDomains":[],"blockedDomains":[],"breakMinutes":5,"priority":"high","selfDepositPoints":1000,"guardianRewardRequestPoints":2000,"goals":[{"id":"goal-1","name":"목표","detail":"","minutes":5,"priority":"high"},{"id":"goal-2","name":"남은 목표","detail":"","minutes":5,"priority":"medium"}],"status":"ready","createdAt":"2026-08-24T09:00:00.000Z","updatedAt":"2026-08-24T09:00:00.000Z"}'::jsonb,'reward-device');

select ok(not has_function_privilege('anon','public.request_planned_guardian_reward(text)','EXECUTE'),'anonymous cannot request reward');
select ok(not has_function_privilege('authenticated','public.start_focus_session_post_start_reward_internal(text,text)','EXECUTE'),'legacy bypass is private');
select throws_ok($$select public.start_focus_session('reward-plan-1','device')$$,'P0001','guardian approval required','cannot start without approval');
select is((select count(*) from public.cloud_focus_sessions),0::bigint,'rejected start creates no session');
select is((select count(*) from public.wallet_transactions where kind='self_deposit_reserved'),0::bigint,'rejected start never reserves student points');
select is((public.request_planned_guardian_reward('reward-plan-1')->>'status'),'pending','request before starting');
select public.request_planned_guardian_reward('reward-plan-1');
select throws_ok($$select public.upsert_focus_plan('reward-plan-1',(select payload from public.cloud_schedules where entity_id='reward-plan-1'),'device')$$,'P0001','focus plan has a pending guardian request','pending request freezes plan');
select is((select count(*) from public.wallet_transactions where kind='guardian_reward_requested'),1::bigint,'duplicate request is idempotent');
create temporary table approval_ids as select id request_id,session_id from public.wallet_transactions where kind='guardian_reward_requested';
select throws_ok($$select public.start_focus_session('reward-plan-1','device')$$,'P0001','guardian approval required','pending request cannot start');
select throws_ok($$select public.approve_guardian_reward_request((select request_id from approval_ids))$$,'P0001','guardian role required','student cannot self approve');
reset role;
set local request.jwt.claim.sub='b2222222-2222-4222-8222-222222222222';
set local role authenticated;
select is((public.approve_guardian_reward_request((select request_id from approval_ids))->>'status'),'approved','guardian approves before session exists');
select public.approve_guardian_reward_request((select request_id from approval_ids));
select is((select count(*) from public.wallet_transactions where kind='guardian_deposit_reserved'),1::bigint,'duplicate approval reserves once');
reset role;
select is((public.get_wallet_balances('b2222222-2222-4222-8222-222222222222')->>'reservedAvailable')::bigint,2000::bigint,'guardian points reserved');
set local request.jwt.claim.sub='b1111111-1111-4111-8111-111111111111';
set local role authenticated;
select is((public.get_planned_guardian_reward('reward-plan-1')->>'status'),'approved','student sees canonical approval');
select throws_ok($$select public.upsert_focus_plan('reward-plan-1',(select payload from public.cloud_schedules where entity_id='reward-plan-1'),'device')$$,'P0001','focus plan has a pending guardian request','approved request freezes plan');
select is((public.start_focus_session('reward-plan-1','device')->>'id'),(select session_id from approval_ids),'start reuses preallocated session id');
select public.start_focus_session('reward-plan-1','device');
reset role;
select is((public.get_wallet_balances('b1111111-1111-4111-8111-111111111111')->>'reservedAvailable')::bigint,1000::bigint,'approved start reserves student deposit');
set local role authenticated;
select is((select count(*) from public.cloud_focus_sessions),1::bigint,'duplicate start creates one session');
select throws_ok($$select public.withdraw_planned_guardian_reward((select request_id from approval_ids))$$,'P0001','reward session already started','cannot withdraw active reward');
select is((public.finish_focus_session((select session_id from approval_ids),array[]::text[],'device')->>'status'),'failed','abandon finishes with failure');
reset role;
select is((public.get_wallet_balances('b2222222-2222-4222-8222-222222222222')->>'topupAvailable')::bigint,10000::bigint,'failure returns entire guardian reservation');
-- Reuse the saved fixture as a fresh ready plan with DNR handshake.
update public.cloud_schedules set entity_id='reward-plan-2',payload=payload||jsonb_build_object('id','reward-plan-2','status','ready','blockingMode','blocklist','blockedDomains',jsonb_build_array(jsonb_build_object('hostname','example.com','includeSubdomains',true)));
set local request.jwt.claim.sub='b1111111-1111-4111-8111-111111111111';
set local role authenticated;
select public.request_planned_guardian_reward('reward-plan-2');
truncate approval_ids;
insert into approval_ids select id,session_id from public.wallet_transactions where schedule_id='reward-plan-2' and kind='guardian_reward_requested';
reset role;
set local request.jwt.claim.sub='b2222222-2222-4222-8222-222222222222';
set local role authenticated;
select public.approve_guardian_reward_request((select request_id from approval_ids));
reset role;
set local request.jwt.claim.sub='b1111111-1111-4111-8111-111111111111';
set local role authenticated;
select is((public.withdraw_planned_guardian_reward((select request_id from approval_ids))->>'status'),'returned','withdraw approved request returns points');
select public.withdraw_planned_guardian_reward((select request_id from approval_ids));
reset role;
select is((select count(*) from public.wallet_transactions where schedule_id='reward-plan-2' and kind='guardian_deposit_returned'),1::bigint,'repeated withdrawal returns once');
select is((public.get_wallet_balances('b2222222-2222-4222-8222-222222222222')->>'topupAvailable')::bigint,10000::bigint,'withdraw restores guardian balance');
set local request.jwt.claim.sub='b1111111-1111-4111-8111-111111111111';
set local role authenticated;
select public.request_planned_guardian_reward('reward-plan-2');
truncate approval_ids;
insert into approval_ids select id,session_id from public.wallet_transactions where schedule_id='reward-plan-2' and kind='guardian_reward_requested' order by created_at desc limit 1;
reset role;
set local request.jwt.claim.sub='b2222222-2222-4222-8222-222222222222';
set local role authenticated;
select public.approve_guardian_reward_request((select request_id from approval_ids));
reset role;
set local request.jwt.claim.sub='b1111111-1111-4111-8111-111111111111';
set local role authenticated;
select is((public.start_focus_session('reward-plan-2','device')->>'status'),'starting','DNR session waits for enforcement');
select is((public.cancel_focus_start((select session_id from approval_ids),'device')->>'status'),'cancelled','failed enforcement cancels funded session');
select public.cancel_focus_start((select session_id from approval_ids),'device');
reset role;
select is((public.get_wallet_balances('b2222222-2222-4222-8222-222222222222')->>'topupAvailable')::bigint,10000::bigint,'failed enforcement refunds guardian reservation');
select is((select count(*) from public.wallet_transactions where session_id=(select session_id from approval_ids) and kind='guardian_deposit_returned'),1::bigint,'failed enforcement refund is idempotent');
select is((select count(*) from public.wallet_transactions where session_id=(select session_id from approval_ids) and kind='guardian_reward_released'),0::bigint,'failed enforcement never pays reward');
select is((select payload->>'status' from public.cloud_schedules where entity_id='reward-plan-2'),'ready','cancelled start restores editable plan');
select is((public.get_wallet_balances('b1111111-1111-4111-8111-111111111111')->>'topupAvailable')::bigint,5000::bigint,'failed enforcement refunds student deposit too');
select is((public.get_wallet_balances('b1111111-1111-4111-8111-111111111111')->>'reservedAvailable')::bigint,0::bigint,'no student reserve remains');
set local request.jwt.claim.sub='b2222222-2222-4222-8222-222222222222';
set local role authenticated;
select throws_ok($$select public.request_planned_guardian_reward('reward-plan-2')$$,'P0001','student role required','guardian cannot request as student');
select throws_ok($$select public.get_planned_guardian_reward('reward-plan-2')$$,'P0001','focus plan not found','other owner cannot read planned reward');
reset role;
set local request.jwt.claim.sub='b1111111-1111-4111-8111-111111111111';
set local role authenticated;
select public.request_planned_guardian_reward('reward-plan-2');
truncate approval_ids;
insert into approval_ids select id,session_id from public.wallet_transactions where schedule_id='reward-plan-2' and kind='guardian_reward_requested' order by created_at desc limit 1;
select is((public.withdraw_planned_guardian_reward((select request_id from approval_ids))->>'status'),'declined','unapproved request can be withdrawn');
select public.withdraw_planned_guardian_reward((select request_id from approval_ids));
select is((select count(*) from public.wallet_transactions where related_transaction_id=(select request_id from approval_ids) and kind='guardian_reward_declined'),1::bigint,'pending withdrawal is idempotent');
reset role;
set local request.jwt.claim.sub='b2222222-2222-4222-8222-222222222222';
set local role authenticated;
select is((public.get_guardian_reward_requests('cancelled')->'items'->0->>'status'),'cancelled','guardian sees cancellation separately from rejection');
select throws_ok($$select public.withdraw_planned_guardian_reward((select request_id from approval_ids))$$,'P0001','reward request not found','guardian cannot withdraw for student');
reset role;
select ok(exists(select 1 from public.notifications where recipient_user_id='b2222222-2222-4222-8222-222222222222' and title='보상 요청이 취소되었습니다'),'guardian receives cancellation notification');
select ok(exists(select 1 from public.notifications where recipient_user_id='b1111111-1111-4111-8111-111111111111' and title='보상 요청이 취소되었습니다'),'student receives cancellation confirmation');
set local request.jwt.claim.sub='b1111111-1111-4111-8111-111111111111';
set local role authenticated;
select public.request_planned_guardian_reward('reward-plan-2');
select public.withdraw_planned_guardian_reward((public.get_planned_guardian_reward('reward-plan-2')->>'requestId')::uuid);
select throws_ok($$select public.request_planned_guardian_reward('reward-plan-2')$$,'P0001','reward request rate limit','sixth new request within five minutes is rejected');
select * from finish();
rollback;
