begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
insert into auth.users(id,email) values ('c1111111-1111-4111-8111-111111111111','push-one@example.com'),('c2222222-2222-4222-8222-222222222222','push-two@example.com');
select ok(not has_function_privilege('authenticated','public.claim_notification_push_batch()','EXECUTE'),'client cannot claim delivery');
select ok(not has_function_privilege('authenticated','public.finish_notification_push(uuid,uuid,uuid,text)','EXECUTE'),'client cannot forge delivery');
select ok(not has_function_privilege('authenticated','public.get_release_operations_snapshot(integer)','EXECUTE'),'operations are service-only');
select ok(public.valid_push_subscription(jsonb_build_object('endpoint','https://fcm.googleapis.com/fcm/send/fixture','keys',jsonb_build_object('p256dh',repeat('B',87),'auth',repeat('A',22)))),'valid subscription accepted');
select ok(not coalesce(public.valid_push_subscription('{"endpoint":"https://127.0.0.1/private","keys":{"p256dh":"wrong","auth":"wrong"}}'),false),'SSRF endpoint blocked');
select ok(not coalesce(public.valid_push_subscription('{"endpoint":"https://fcm.googleapis.com/x"}'),false),'missing encryption keys fail closed');
set local request.jwt.claim.sub='c1111111-1111-4111-8111-111111111111';
set local role authenticated;
select ok(public.set_push_subscription('web-push:c1111111-1111-4111-8111-111111111111',jsonb_build_object('endpoint','https://fcm.googleapis.com/fcm/send/fixture','keys',jsonb_build_object('p256dh',repeat('B',87),'auth',repeat('A',22)))),'owner registers device');
set local request.jwt.claim.sub='c2222222-2222-4222-8222-222222222222';
select ok(public.set_push_subscription('web-push:c1111111-1111-4111-8111-111111111111',null),'foreign revoke changes no row');
reset role;
select is((select count(*) from public.devices where push_subscription is not null and user_id='c1111111-1111-4111-8111-111111111111'),1::bigint,'foreign caller cannot revoke owner subscription');
select public.create_notification('c1111111-1111-4111-8111-111111111111',null,'focus_completed','private goal title','private reward amount','{}'::jsonb,'push-test');
create temporary table claimed as select public.claim_notification_push_batch() jobs;
select is(jsonb_array_length((select jobs from claimed)),1,'one canonical event-device job');
select is(public.claim_notification_push_batch(),'[]'::jsonb,'concurrent scan cannot repeat leased job');
select ok(not public.finish_notification_push(((select jobs from claimed)#>>'{0,notificationId}')::uuid,((select jobs from claimed)#>>'{0,deviceId}')::uuid,gen_random_uuid(),'sent'),'wrong lease token rejected');
select ok(public.finish_notification_push(((select jobs from claimed)#>>'{0,notificationId}')::uuid,((select jobs from claimed)#>>'{0,deviceId}')::uuid,((select jobs from claimed)#>>'{0,token}')::uuid,'expired'),'expired device is removed');
select is((select count(*) from public.devices where push_subscription is not null),0::bigint,'expired endpoint no longer delivered');
select is((select data from public.notifications where dedupe_key='push-test'),'{}'::jsonb,'public notification payload is unchanged');
select ok(public.get_release_operations_snapshot() ? 'issueCount','read-only operations returns count');
select ok(not (public.get_release_operations_snapshot()::text like '%private goal%'),'operations omit raw titles');
set local request.jwt.claim.sub='c1111111-1111-4111-8111-111111111111';
set local role authenticated;
select ok(public.revoke_all_push_subscriptions(),'logout revocation is idempotent');
select * from finish(); rollback;
